kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
<<<<<<< HEAD
      tier: db 
    template:
=======
      tier: db
  # pod definition
  template:
>>>>>>> dd9fefa53e963b63b36647d1fed019547d5cbde3
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
<<<<<<< HEAD
  Namespace: expense
=======
  namespace: expense
>>>>>>> dd9fefa53e963b63b36647d1fed019547d5cbde3
spec:
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port
